name: 'Statusoli'
description: 'Get Build Status-es as a Telegram Message in a more of a Malayali Way'
author: 'athul'
inputs: 
  chat:
    description: 'Chat to send: chat id or @channel_name'
    required: true
  token:
    description: 'Telegram Bot token'
    required: true
  status:
    description: 'Job status'
    required: true
  i_body:
    description: 'Boddy of the Issue'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
